---
abstract: 'The Catalyst Framework Runtime'
author:
  - 'Catalyst Contributors, see Catalyst.pm'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.46
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Runtime
no_index:
  directory:
    - inc
    - t
requires:
  CGI::Simple::Cookie: 0
  Carp: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::Inspector: 1.06
  Data::Dump: 0
  File::Modified: 0
  HTML::Entities: 0
  HTTP::Body: 1.04
  HTTP::Headers: 1.64
  HTTP::Request: 0
  HTTP::Request::AsCGI: 0.5
  HTTP::Response: 0
  LWP::UserAgent: 0
  Module::Pluggable: 3.01
  NEXT: 0
  Path::Class: 0.09
  Scalar::Util: 0
  Text::Balanced: 0
  Text::SimpleTable: 0.03
  Time::HiRes: 0
  Tree::Simple: 1.15
  Tree::Simple::Visitor::FindByPath: 0
  URI: 1.35
  perl: 5.8.1
resources:
  IRC: irc://irc.perl.org/#catalyst
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst
  homepage: http://dev.catalyst.perl.org/
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Runtime/
version: 5.71000
