---
abstract: 'The Catalyst Framework Runtime'
author:
  - '& COPYRIGHT'
build_requires:
  Class::Data::Inheritable: 0
  Data::Dump: 0
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::Common: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Runtime
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::EndOfScope: 0.08
  CGI::Simple::Cookie: 1.109
  Carp: 0
  Class::C3::Adopt::NEXT: 0.07
  Class::MOP: 0.95
  Data::Dump: 0
  Data::OptList: 0
  HTML::Entities: 0
  HTML::HeadParser: 0
  HTTP::Body: 1.06
  HTTP::Headers: 1.64
  HTTP::Request: 5.814
  HTTP::Request::AsCGI: 1.0
  HTTP::Response: 5.813
  LWP::UserAgent: 0
  List::MoreUtils: 0
  MRO::Compat: 0
  Module::Pluggable: 3.9
  Moose: 1.03
  MooseX::Emulate::Class::Accessor::Fast: 0.00903
  MooseX::Getopt: 0.30
  MooseX::MethodAttributes::Inheritable: 0.24
  MooseX::Role::WithOverloading: 0.09
  MooseX::Types: 0
  MooseX::Types::Common::Numeric: 0
  MooseX::Types::LoadableClass: 0.003
  Path::Class: 0.09
  Plack: 0.9974
  Plack::Middleware::ReverseProxy: 0.04
  Plack::Test::ExternalServer: 0
  Scalar::Util: 0
  String::RewritePrefix: 0.004
  Sub::Exporter: 0
  Task::Weaken: 0
  Text::Balanced: 0
  Text::SimpleTable: 0.03
  Time::HiRes: 0
  Tree::Simple: 1.15
  Tree::Simple::Visitor::FindByPath: 0
  Try::Tiny: 0
  URI: 1.35
  namespace::autoclean: 0.09
  namespace::clean: 0.13
  perl: 5.8.4
resources:
  IRC: irc://irc.perl.org/#catalyst
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst
  homepage: http://dev.catalyst.perl.org/
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-Runtime.git
version: 5.89003
